apiVersion: api/v1
kind: Deployment
metadata:
  name: fplfriend-api
  labels:
    app: fplfriend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: fplfriend.azurecr.io/fplfriend-api:latest
        ports:
        - containerPort: 4500